MemsAdminBundle_admin_mems_admin_bundle_user:
    resource: "@MemsAdminBundle/Controller/User/"
    type:     admingenerator
    prefix:   /admin/user

MemsAdminBundle_admin_mems_admin_bundle_comment:
    resource: "@MemsAdminBundle/Controller/Comment/"
    type:     admingenerator
    prefix:   /admin/comment

MemsAdminBundle_admin_mems_admin_bundle_mem:
    resource: "@MemsAdminBundle/Controller/Mem/"
    type:     admingenerator
    prefix:   /admin/mem

mems_layout:
    resource: "@MemsLayoutBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

mems_user:
    resource: "@MemsUserBundle/Resources/config/routing.yml"
    prefix:   /

mems_admin:
    resource: "@MemsAdminBundle/Resources/config/routing.yml"
    prefix:   /
    
mems_mems:
    resource: "@MemsMemsBundle/Resources/config/routing.yml"
    prefix:   /

hwi_oauth_security:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix: /login
 
hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix: /login
 
hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /login
 
facebook_login:
    pattern: /login/facebook