MemsAdminBundle_admin_mems_admin_bundle_mem:
    resource: "@MemsAdminBundle/Controller/Mem/"
    type:     admingenerator
    prefix:   /admin/mems_admin_bundle/mem

mems_layout:
    resource: "@MemsLayoutBundle/Resources/config/routing.yml"
    prefix:   /

mems_mems:
    resource: "@MemsMemsBundle/Resources/config/routing.yml"
    prefix:   /

mems_user:
    resource: "@MemsUserBundle/Resources/config/routing.yml"
    prefix:   /

mems_admin:
    resource: "@MemsAdminBundle/Resources/config/routing.yml"
    prefix:   /

