mems_layout:
    resource: "@MemsLayoutBundle/Resources/config/routing.yml"
    prefix:   /

mems_mems:
    resource: "@MemsMemsBundle/Resources/config/routing.yml"
    prefix:   /

mems_user:
    resource: "@MemsUserBundle/Resources/config/routing.yml"
    prefix:   /

mems_admin:
    resource: "@MemsAdminBundle/Resources/config/routing.yml"
    prefix:   /

