MemsAdminBundle_admin_mems_admin_bundle_mem:
    resource: "@MemsAdminBundle/Controller/Mem/"
    type:     admingenerator
    prefix:   /admin/mem

mems_layout:
    resource: "@MemsLayoutBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

mems_user:
    resource: "@MemsUserBundle/Resources/config/routing.yml"
    prefix:   /

mems_admin:
    resource: "@MemsAdminBundle/Resources/config/routing.yml"
    prefix:   /
    
mems_mems:
    resource: "@MemsMemsBundle/Resources/config/routing.yml"
    prefix:   /
