parameters:
#    mems_core.example.class: Shop\CoreBundle\Example

services:
#    mems_core.example:
#        class: %mems_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
