mems_mems_homepage:
    path:     /hello/{name}
    defaults: { _controller: MemsMemsBundle:Default:index }

mems_add:
    path:     /panel/add
    defaults: { _controller: MemsMemsBundle:Mems:add }

mems_list:
    path:     /{page}
    defaults: { _controller: MemsMemsBundle:Mems:list, page: 1 }
    requirements: { page: \d+ }
    
mems_unaccepted_list:
    path:     /poczekalnia/{page}
    defaults: { _controller: MemsMemsBundle:Mems:listUnaccepted, page: 1 }
    requirements: { page: \d+ }

mems_new:
    path:     /new
    defaults: { _controller: MemsMemsBundle:Comment:new }

mems_edit:
    path:     /edit/{id}
    defaults: { _controller: MemsMemsBundle:Comment:edit }

mems_show_rand:
    path:     /losuj
    defaults: { _controller: MemsMemsBundle:Mems:showRandom }      

mems_top:
    path:     /top
    defaults: { _controller: MemsMemsBundle:Mems:top }

mems_show:
    path:     /{slug}
    defaults: { _controller: MemsMemsBundle:Mems:show }
    

    
  